# Kai Tak

Kai Tak is a neighborhood in Kowloon, Hong Kong. One of the highlights of Kai Tak used to be it's airport, which holds a special place in aviation history due to its unique and challenging approach, which involved pilots making a steep descent over a densely populated area while making a sharp turn at the same time and then landing on a single runway that jutted out into Victoria Harbor.
[Landing at Kai Tak Airport | YouTube](https://www.youtube.com/watch?v=OtnL4KYVtDE)

In 1998 the new Hong Kong International Airport opened, and operations at Kai Tak Airport were ceased. After the closure, the former Kai Tak Airport and surrounding neighborhood underwent a massive redevelopment project to transform it into a new residential and commercial district, which is still continuing today.

Have a look at the [Kai Tak Speckle Project](https://app.speckle.systems/projects/013aaf06e7/models/0e43d1f003,a739490298) to get an idea what Kai Tak looks like now. (Developents are going fast, so [Google Earth 3D](https://www.google.com/maps/@22.3065043,114.2020499,462a,35y,343.1h,75.5t/data=!3m1!1e3?entry=ttu) is a bit outdated.)

Ground Investigation Data for Hong Kong can be found here:  
[GEO Data for Public Use](https://www.ginfo.cedd.gov.hk/GEOOpenData/eng/Default.aspx)

In [1]:
import bedrock.gi as brgi
import requests

In [14]:
data_root = "https://github.com/bedrock-engineer/bedrock-web/raw/main/public/gi-data/kaitak"
report_number = 31241
file_name = "GE9908.7.ags"
data_url = f"{data_root}/{str(report_number)}/{file_name}"

response = requests.get(data_url)

if response.status_code == 200:
    ags3_str = response.content.decode("utf-8")
else:
    print(f"Failed to retrieve data: {response.status_code}")

In [15]:
data_url

'https://github.com/bedrock-engineer/bedrock-web/raw/main/public/gi-data/kaitak/31241/GE9908.7.ags'

In [4]:
ags3_dfs = brgi.ags3_to_dfs(ags3_str)

No data was found on line 3. Last Group: PROJ
No data was found on line 43. Last Group: HOLE
No data was found on line 44. Last Group: HOLE
No data was found on line 45. Last Group: HOLE
No data was found on line 84. Last Group: PTIM
No data was found on line 125. Last Group: SAMP
No data was found on line 194. Last Group: GEOL
No data was found on line 195. Last Group: GEOL
No data was found on line 196. Last Group: GEOL
No data was found on line 197. Last Group: GEOL
No data was found on line 198. Last Group: GEOL
No data was found on line 199. Last Group: GEOL

In [10]:
ags3_dfs.keys()

dict_keys(['PROJ', 'HOLE', 'PTIM', 'SAMP', 'GEOL'])

In [12]:
ags3_dfs["HOLE"].columns

Index(['HOLE_ID', 'HOLE_TYPE', 'HOLE_NATE', 'HOLE_NATN', 'HOLE_GL',
       'HOLE_FDEP', 'HOLE_STAR', 'HOLE_LOG', 'HOLE_REM', 'HOLE_LOCX',
       'HOLE_LOCY', 'HOLE_LOCZ', 'HOLE_ENDD', 'HOLE_BACD', 'HOLE_CREW',
       'HOLE_ORNT', 'HOLE_INCL', 'HOLE_EXC', 'HOLE_SHOR",', 'HOLE_STAB',
       'HOLE_DIMW', 'HOLE_DIML'],
      dtype='object')

In [13]:
ags3_dfs["HOLE"]

,HOLE_ID,HOLE_TYPE,HOLE_NATE,HOLE_NATN,HOLE_GL,HOLE_FDEP,HOLE_STAR,HOLE_LOG,HOLE_REM,HOLE_LOCX,...,HOLE_ENDD,HOLE_BACD,HOLE_CREW,HOLE_ORNT,HOLE_INCL,HOLE_EXC,"HOLE_SHOR"",",HOLE_STAB,HOLE_DIMW,HOLE_DIML
0,AC1,VC,838804.86,820146.79,-4.40,6.00,16/06/2000,MY LEE,1. Sub-samples were taken at A) 0.10m to 1.10m...,,...,16/06/2000,16/06/2000,,000,90,G35,,,,
1,AC2(B),VC,838924.24,819940.24,-2.00,6.00,17/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 1.00m...,,...,17/06/2000,17/06/2000,,000,90,G35,,,,
2,AC3,VC,839082.41,819958.33,-4.80,6.00,17/06/2000,MY LEE,1. Sub-samples were taken at A) 0.20m to 1.20m...,,...,17/06/2000,17/06/2000,,000,90,G35,,,,
3,AC4(A),VC,839202.72,819766.02,-4.75,6.00,19/06/2000,MY LEE,1. Sub-samples were taken at A) 0.25m to 1.25m...,,...,19/06/2000,19/06/2000,,000,90,G35,,,,
4,AC5,VC,839315.26,819565.15,-3.20,11.00,16/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 0.75m...,,...,16/06/2000,16/06/2000,,000,90,DM2,,,,
5,AC6,VC,839478.85,819577.05,-6.10,5.00,17/06/2000,MY LEE,1. Sub-samples were taken at A) 0.25m to 0.85m...,,...,17/06/2000,17/06/2000,,000,90,DM2,,,,
6,AC7(B),VC,839599.62,819393.66,-6.10,5.00,17/06/2000,MY LEE,1. Sub-samples were taken at A) 0.65m to 1.45m...,,...,17/06/2000,17/06/2000,,000,90,DM2,,,,
7,KB1,VC,837972.72,818966.22,-7.90,6.00,21/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 0.90m...,,...,21/06/2000,21/06/2000,,000,90,DM2,,,,
8,KB2(A),VC,838048.56,819357.17,-6.80,5.50,21/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 0.74m...,,...,21/06/2000,21/06/2000,,000,90,DM2,,,,
9,KB3,VC,838045.89,819656.72,-6.70,4.00,21/06/2000,MY LEE,1. Sub-samples were taken at A) 0.05m to 0.51m...,,...,21/06/2000,21/06/2000,,000,90,DM2,,,,
10,KB4,VC,838450.29,819374.58,-7.10,4.50,22/06/2000,MY LEE,1. Sub-samples were taken at A) 0.10m to 0.63m...,,...,22/06/2000,22/06/2000,,000,90,DM2,,,,
11,KB5(A),VC,838271.87,819591.33,-6.00,6.00,22/06/2000,MY LEE,1. Sub-samples were taken at A) 0.10m to 0.43m...,,...,22/06/2000,22/06/2000,,000,90,DM2,,,,
12,KB6(A),VC,838350.72,819973.01,-1.90,6.00,20/06/2000,MY LEE,1. Sub-samples were taken at A) 0.10m to 0.70m...,,...,20/06/2000,20/06/2000,,000,90,DM2,,,,
13,KB7,VC,838659.40,819678.09,-4.20,6.00,20/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 0.55m...,,...,20/06/2000,20/06/2000,,000,90,DM2,,,,
14,KT1,VC,839914.66,819393.56,-5.75,6.00,19/06/2000,MY LEE,1. Sub-samples were taken at A) 0.30m to 0.60m...,,...,19/06/2000,19/06/2000,,000,90,DM2,,,,
15,KT2,VC,840073.08,819241.19,-5.60,6.00,19/06/2000,MY LEE,1. Sub-samples were taken at A) 0.35m to 0.92m...,,...,19/06/2000,19/06/2000,,000,90,DM2,,,,
16,KT3,VC,841064.83,818296.58,-10.20,4.50,20/06/2000,MY LEE,1. Sub-samples were taken at A) 0.10m to 1.10m...,,...,20/06/2000,20/06/2000,,000,90,DM2,,,,
17,KT4,VC,840912.49,818138.16,-8.00,6.00,19/06/2000,MY LEE,1. Sub-samples were taken at A) 0.00m to 1.00m...,,...,19/06/2000,19/06/2000,,000,90,DM2,,,,